[package]
name = "estudely-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
magic-wormhole.workspace = true
tokio.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
async-std = { version = "1", features = ["attributes"] }
futures = "0.3"
tempfile = "3"
